http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  usersEndpoint:
    host: localhost
    paths: '/users'
  uuidEndPoint:
    host: localhost
    paths: '/uuid'
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  uuidService:
    url: 'https://httpbin.org'
  usersService:
    url: 'https://localhost:3001'
  httpbin:
    url: 'https://httpbin.org'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - usersEndPoint
    policies:
      - proxy:
          -action:
              serviceEndpoint: usersService
              changeOrigin: false
  uuidPipeline:
    apiEndpoints:
      - uuidEndPoint
    policies:
      - proxy:
          - action:
              serviceEndpoint: uuidService
              changeOrigin: true